### ISSUE TITLE
[tracking] AIP#61 - AdEx v5: significantly cheaper channels

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator#338]
Tracking issue for the changes regarding [AIP#61: AdEx v5: significantly cheaper channels (full details here)](https://github.com/AdExNetwork/aips/issues/61)
- [ ] Withdrawals of advertiser funds (new event)
- [ ] Sentry
  - [ ] GET /channel/:id/spender/:addr
  - [ ] GET /channel/:id/spender/all
  - [ ] POST /channel/:id/spender/:addr
  - [ ] POST Campaign (modify / submit)
  - [ ] Enforce limits
  - [ ] Events - enforce per-campaign spending limits atomically
  - [ ] Distribute fees
  - [ ] Analytics breakdowns by 1hr
- [ ] Validator
  - [ ] Unified precision 
  - [ ] BalanceAggregates
  - [ ] Double-check per-spender limits
  - [ ] Remove Fees (and move to Sentry)
  - [ ] Worker flow
  - [ ] Outpace - spender & earner limits
- [ ] Adapter
  - [ ] Calculate total spendable amount
  - [ ] Fakereum
